#!/bin/bash
cmd.exe /c start /B x410.exe /wm /public
cmd.exe /c start "" /B "pulseaudio.exe"
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0;  export PULSE_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}')
$1
pids=`ps -ef | grep $@ | tr -s " " | cut -d" " -f2 | head -n 3 | tail -n 2`
for pid in ${pids[*]}; do
    while kill -0 "$pid" 2>/dev/null; do sleep 1; done
done
cmd.exe /c taskkill.exe /IM x410.exe /F
cmd.exe /c taskkill.exe /IM pulseaudio.exe /F

